CREATE TABLE "BANKADMIN"."CLIENT" 
   (	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BIRTHDATE" DATE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE TRIGGER "BANKADMIN"."CLIENT_TRG" 
BEFORE INSERT ON CLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CLIENT_ID IS NULL THEN
      SELECT CLIENT_SEQ1.NEXTVAL INTO :NEW.CLIENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "BANKADMIN"."CLIENT_TRG" ENABLE;  
  
  
  CREATE TABLE "BANKADMIN"."ACCOUNT" 
   (	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"BALANCE" NUMBER(10,4) NOT NULL ENABLE, 
	"TYPE_ACCOUNT" CHAR(1 BYTE) NOT NULL ENABLE, 
	"STATUS_ACCOUNT" CHAR(1 BYTE), 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CLIENT_FK" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "BANKADMIN"."CLIENT" ("CLIENT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
    CREATE TABLE "BANKADMIN"."TRANSACTION" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"SOURCE_ACCOUNT" NUMBER NOT NULL ENABLE, 
	"DESTINATION_ACCOUNT" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_DATE" DATE NOT NULL ENABLE, 
	"TYPE_TRANSACTION" CHAR(1 BYTE) NOT NULL ENABLE, 
	"TRANSACTION_AMOUNT" NUMBER(10,4), 
	 CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SOURCE_ACCOUNT_FK" FOREIGN KEY ("SOURCE_ACCOUNT")
	  REFERENCES "BANKADMIN"."ACCOUNT" ("ACCOUNT_ID") ENABLE, 
	 CONSTRAINT "TRANSACTION_FK1" FOREIGN KEY ("DESTINATION_ACCOUNT")
	  REFERENCES "BANKADMIN"."ACCOUNT" ("ACCOUNT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
